name: "Generate & update markdown content"
description: "Automatically generate and update markdown content like a README.md"
author: "Trinh Minh Triet"
branding:
  icon: "file-text"
  color: "green"

inputs:
  template:
    description: "Which template to use"
    default: "README.md.tpl"
    required: false
  writeTo:
    description: "Where to render the template to"
    default: "README.md"
    required: false

outputs:
  modified:
    description: "Which files were modified"

runs:
  using: "docker"
  image: "docker://trinhminhtriet/markgen"
  args:
    - "-write"
    - ${{ inputs.writeTo }}
    - ${{ inputs.template }}
