name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: trinhminhtriet/readme-markgen-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          template: "test/README.md.tpl"
          writeTo: "test/README.md"

      - name: Check outputs and modified files
        run: |
          cat test/README.md
